/*
 * generated by Xtext
 */
package smdp.project.survey.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SurveyDSLUiModule extends smdp.project.survey.ui.AbstractSurveyDSLUiModule {
	public SurveyDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
