/*
* generated by Xtext
*/
package smdp.project.survey;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class SurveyDSLUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return smdp.project.survey.ui.internal.SurveyDSLActivator.getInstance().getInjector("smdp.project.survey.SurveyDSL");
	}
	
}
