/**
 * generated by Xtext
 */
package smdp.project.survey.ui.contentassist;

import smdp.project.survey.ui.contentassist.AbstractSurveyDSLProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class SurveyDSLProposalProvider extends AbstractSurveyDSLProposalProvider {
}
