/**
 * generated by Xtext
 */
package smdp.project.survey.serializer;

import smdp.project.survey.serializer.AbstractSurveyDSLSyntacticSequencer;

@SuppressWarnings("all")
public class SurveyDSLSyntacticSequencer extends AbstractSurveyDSLSyntacticSequencer {
}
