/**
 * generated by Xtext
 */
package smdp.project.survey.serializer;

import smdp.project.survey.serializer.AbstractSurveyDSLSemanticSequencer;

@SuppressWarnings("all")
public class SurveyDSLSemanticSequencer extends AbstractSurveyDSLSemanticSequencer {
}
