/*
 * generated by Xtext
 */
package smdp.project.survey.validation

import org.eclipse.xtext.validation.Check
import survey.MultipleChoice
import org.eclipse.emf.ecore.EObject
import survey.RadioChoice
import survey.OpenQuestion

//import org.eclipse.xtext.validation.Check

/**
 * Custom validation rules. 
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
class SurveyDSLValidator extends AbstractSurveyDSLValidator {   
    @Check
    def static dispatch constraint(MultipleChoice choice) {
    	!choice.description.trim.equals("") && 
    	choice.answers.forall[!choice.requiredPreviousAnswers.contains(it) && !it.description.trim.equals("")]
	}
	
	@Check
    def static dispatch constraint(RadioChoice choice) {
    	!choice.description.trim.equals("") && 
    	choice.answers.forall[!choice.requiredPreviousAnswers.contains(it) && !it.description.trim.equals("")]
	}
	
	@Check
    def static dispatch constraint(OpenQuestion choice) {
    	!choice.description.trim.equals("") && 
    	!choice.requiredPreviousAnswers.contains(choice.openAnswer)
	}
	
	@Check
	def static dispatch boolean constraint(EObject it) {
		true
	}
	
}
