/*
 * generated by Xtext
 */
package smdp.project.survey;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SurveyDSLRuntimeModule extends smdp.project.survey.AbstractSurveyDSLRuntimeModule {

}
