/*
* generated by Xtext
*/
package smdp.project.survey;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class SurveyDSLStandaloneSetup extends SurveyDSLStandaloneSetupGenerated{

	public static void doSetup() {
		new SurveyDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

