/**
 * generated by Xtext
 */
package smdp.project.survey.validation;

import smdp.project.survey.validation.AbstractSurveyDSLValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class SurveyDSLValidator extends AbstractSurveyDSLValidator {
}
